"""add foundation domain models

Revision ID: 6e6ef9fcee77
Revises: 7412438bd471
Create Date: 2026-04-16 00:22:07.160588

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "6e6ef9fcee77"
down_revision: Union[str, Sequence[str], None] = "7412438bd471"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", AutoString(), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "OPEN", "DONE", name="requirementstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_requirement_id"), "requirement", ["id"], unique=False)
    op.create_index(
        op.f("ix_requirement_project_id"), "requirement", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_requirement_status"), "requirement", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_requirement_title"), "requirement", ["title"], unique=False
    )
    op.create_table(
        "resourcelink",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", AutoString(), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("url", AutoString(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("REPOSITORY", "DOCUMENTATION", "MISC", name="resourcelinkcategory"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_resourcelink_id"), "resourcelink", ["id"], unique=False)
    op.create_index(
        op.f("ix_resourcelink_project_id"), "resourcelink", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_resourcelink_title"), "resourcelink", ["title"], unique=False
    )
    op.create_table(
        "workitem",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("parent_work_item_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("MILESTONE", "WORK_PACKAGE", "TASK", name="workitemtype"),
            nullable=False,
        ),
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("planned_start_date", sa.Date(), nullable=True),
        sa.Column("planned_end_date", sa.Date(), nullable=True),
        sa.Column("current_start_date", sa.Date(), nullable=True),
        sa.Column("current_end_date", sa.Date(), nullable=True),
        sa.Column("effort_estimate_hours", sa.Float(), nullable=True),
        sa.Column("responsible_person", AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "TODO",
                "IN_PROGRESS",
                "IN_REVIEW",
                "DONE",
                "BEHIND_SCHEDULE",
                name="workitemstatus",
            ),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_work_item_id"],
            ["workitem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workitem_current_end_date"),
        "workitem",
        ["current_end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workitem_current_start_date"),
        "workitem",
        ["current_start_date"],
        unique=False,
    )
    op.create_index(op.f("ix_workitem_id"), "workitem", ["id"], unique=False)
    op.create_index(op.f("ix_workitem_name"), "workitem", ["name"], unique=False)
    op.create_index(
        op.f("ix_workitem_parent_work_item_id"),
        "workitem",
        ["parent_work_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workitem_planned_end_date"),
        "workitem",
        ["planned_end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workitem_planned_start_date"),
        "workitem",
        ["planned_start_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workitem_project_id"), "workitem", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_workitem_status"), "workitem", ["status"], unique=False)
    op.create_index(op.f("ix_workitem_type"), "workitem", ["type"], unique=False)
    op.create_table(
        "requirementworkitemlink",
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("work_item_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["workitem.id"],
        ),
        sa.PrimaryKeyConstraint("requirement_id", "work_item_id"),
    )
    op.add_column("project", sa.Column("tags", AutoString(), nullable=True))
    op.add_column("project", sa.Column("notes", AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "notes")
    op.drop_column("project", "tags")
    op.drop_table("requirementworkitemlink")
    op.drop_index(op.f("ix_workitem_type"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_status"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_project_id"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_planned_start_date"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_planned_end_date"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_parent_work_item_id"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_name"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_id"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_current_start_date"), table_name="workitem")
    op.drop_index(op.f("ix_workitem_current_end_date"), table_name="workitem")
    op.drop_table("workitem")
    op.drop_index(op.f("ix_resourcelink_title"), table_name="resourcelink")
    op.drop_index(op.f("ix_resourcelink_project_id"), table_name="resourcelink")
    op.drop_index(op.f("ix_resourcelink_id"), table_name="resourcelink")
    op.drop_table("resourcelink")
    op.drop_index(op.f("ix_requirement_title"), table_name="requirement")
    op.drop_index(op.f("ix_requirement_status"), table_name="requirement")
    op.drop_index(op.f("ix_requirement_project_id"), table_name="requirement")
    op.drop_index(op.f("ix_requirement_id"), table_name="requirement")
    op.drop_table("requirement")
    # ### end Alembic commands ###
