"""initial migration

Revision ID: 7412438bd471
Revises:
Create Date: 2026-04-15 23:16:20.985905

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7412438bd471"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "customer_type",
            sa.Enum(
                "INDIVIDUAL",
                "CORPORATE",
                "GOVERNMENT",
                "NON_PROFIT",
                name="customertype",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("internal_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_id"), "customer", ["id"], unique=False)
    op.create_index(
        op.f("ix_customer_is_active"), "customer", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_customer_name"), "customer", ["name"], unique=False)
    op.create_table(
        "project",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNING",
                "ACTIVE",
                "ON_HOLD",
                "COMPLETED",
                "CANCELLED",
                name="projectstatus",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_customer_id"), "project", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_project_id"), "project", ["id"], unique=False)
    op.create_index(
        op.f("ix_project_is_archived"), "project", ["is_archived"], unique=False
    )
    op.create_index(op.f("ix_project_name"), "project", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_name"), table_name="project")
    op.drop_index(op.f("ix_project_is_archived"), table_name="project")
    op.drop_index(op.f("ix_project_id"), table_name="project")
    op.drop_index(op.f("ix_project_customer_id"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_customer_name"), table_name="customer")
    op.drop_index(op.f("ix_customer_is_active"), table_name="customer")
    op.drop_index(op.f("ix_customer_id"), table_name="customer")
    op.drop_table("customer")
    # ### end Alembic commands ###
