"""updated customer project relationship to linking table

Revision ID: f5f88aecc9cc
Revises: 6e6ef9fcee77
Create Date: 2026-04-16 00:39:03.817705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f88aecc9cc'
down_revision: Union[str, Sequence[str], None] = '6e6ef9fcee77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectcustomerlink',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'customer_id')
    )
    op.drop_index(op.f('ix_project_customer_id'), table_name='project')
    op.drop_constraint(op.f('project_customer_id_fkey'), 'project', type_='foreignkey')
    op.drop_column('project', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('project_customer_id_fkey'), 'project', 'customer', ['customer_id'], ['id'])
    op.create_index(op.f('ix_project_customer_id'), 'project', ['customer_id'], unique=False)
    op.drop_table('projectcustomerlink')
    # ### end Alembic commands ###
